meta:
  version: 3
  flow: Chip
  substituting_steps:

    #Magic.*: null
    #Netgen.*: null

    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null

    # Disable KLayout DRC
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # Disable magic DRC
    # Magic.DRC: null
    #Checker.MagicDRC: null

    # Disable KLayout antenna check
    KLayout.Antenna: null
    Checker.KLayoutAntenna: null

    # Disable KLayout density check
    #KLayout.Density: null
    #Checker.KLayoutDensity: null
    
    # Save time
    OpenROAD.IRDropReport: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv
- dir::../src/analog_dummy.v
- dir::../src/chip_core.sv

VERILOG_DEFINES: [FUNCTIONAL]

# Enable plugin for better SystemVerilog support
# USE_SLANG: True
# SLANG_ARGUMENTS: ['--keep-hierarchy']

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# Specify the pad instances for the padring
# Signal, AVDD, txp, txn, VSS, clkp, clkn, vss
PAD_SOUTH: [
    "analogs\\[0\\].analog_pad",

    "vdda\\[0\\].vdda_pad",
    "tx_p_pad",   
    "tx_n_pad", 
    "vssa\\[0\\].vssa_pad",
    clk_p_pad,
    clk_n_pad,
    "vssa\\[1\\].vssa_pad"
]

PAD_EAST: [
    "analogs\\[1\\].analog_pad",
    "analogs\\[2\\].analog_pad",
    "iovdda\\[0\\].iovdda_pad",
    "iovssa\\[0\\].iovssa_pad",

    "vssa\\[2\\].vssa_pad",
    rx_n_pad,
    rx_p_pad, 
    "vssa\\[3\\].vssa_pad"
]
# TODO: replace IO analog power pads with IO digital power
PAD_NORTH: [
    "bidirs\\[6\\].bidir_pad", 
    "bidirs\\[7\\].bidir_pad", 
    rst_n_pad,

    "iovdda\\[1\\].iovdda_pad",
    "iovssa\\[1\\].iovssa_pad",

    "bidirs\\[0\\].bidir_pad", 
    "bidirs\\[1\\].bidir_pad", 
    "bidirs\\[2\\].bidir_pad"
]
# TODO: replace analog power pads with digital power
PAD_WEST: [
    "inputs\\[0\\].input_pad",
    "inputs\\[1\\].input_pad",
    "outputs\\[0\\].output_pad", 

    "vdda\\[1\\].vdda_pad",
    "vssa\\[4\\].vssa_pad",
    
    "bidirs\\[3\\].bidir_pad", 
    "bidirs\\[4\\].bidir_pad", 
    "bidirs\\[5\\].bidir_pad" 
]

PAD_CFG: dir::pad_cfg.tcl

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Clock
CLOCK_NET: m_analog/digital_clk_o
CLOCK_PORT: m_analog/digital_clk_o

CLOCK_PERIOD: 20

# Floorplanning
FP_SIZING: absolute
# for the sealring on all sides
DIE_AREA: [0, 0, 1580, 1580]
CORE_AREA: [365, 365, 1215, 1215]

# Increase for more logic
# on your die
PL_TARGET_DENSITY_PCT: 10
GRT_ALLOW_CONGESTION: true

# PDN
PDN_CORE_RING: True

# Override bondpad name
PAD_BONDPAD_NAME: bondpad_70x70_5L

# Bondpad is not yet included in the PDK
EXTRA_GDS:
- dir::../ip/bondpad_70x70/gds/bondpad_70x70_5L.gds

EXTRA_LEFS:
- dir::../ip/bondpad_70x70/lef/bondpad_70x70_5L.lef

IGNORE_DISCONNECTED_MODULES:
- bondpad_70x70_5L

# Power / ground nets
# TODO: add back digital power
VDD_NETS:
- VDDA
#- VDDD
GND_NETS:
- VSSA
#- VSSD
#
PDN_CFG: dir::pdn_cfg.tcl

# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 15
PDN_CORE_RING_HWIDTH: 15
# Ensure minimum spacing for long metals
PDN_CORE_RING_VSPACING: 5
PDN_CORE_RING_HSPACING: 5

PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_ENABLE_PINS: False

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

